import type { Metadata } from "next";
import { Lora, Martel } from "next/font/google";

import "./globals.css";

const display = Martel({
  weight: "900",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-display",
});

const serif = Lora({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${serif.className} ${display.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
